
import {JetBrains_Mono} from "next/font/google";
import "./globals.css";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const JetBrainsMono  = JetBrains_Mono({
  subsets:["latin"],
  weight: ["100","200","300","400","500","600","700","800"],
  variable: "--font-jetbrainsMono",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={JetBrainsMono.variable}>{children}</body>
    </html>
  )
}
